### ISSUE TITLE
import Transport from 'winston-transport'; error: has no default export

### ISSUE THREAD

**Issue by Fuco1** [Its-Alex/winston-node-sentry#1] opened 2019-02-22 14:03 UTC
I'm importing

```ts
import { SentryTransport } from 'winston-node-sentry/dist';
```

when I do a typecheck with `tsc` I get

```
$ tsc --noEmit
node_modules/winston-node-sentry/dist/index.d.ts:1:8 - error TS1192: Module '"/home/matus/dev/baas-serverless/node_modules/winston-transport/index"' has no default export.

1 import Transport from 'winston-transport';
         ~~~~~~~~~


Found 1 error.
```

**Comment by Fuco1** [comment] 2019-02-22 14:06
Changing the line in the file to 

```
import * as Transport from 'winston-transport';
```
seems to fix the issue.

**Comment by Its-Alex** [comment] 2019-02-22 14:37
What's your problem ?

Because I always have an error about `winston-transport` if I use your solution I has error about it too.

```
$ tsc --noEmit dist/index.d.ts
dist/index.d.ts:11:56 - error TS2339: Property 'default' does not exist on type 'typeof TransportStream'.

11 export declare class SentryTransport extends Transport.default {
                                                          ~~~~~~~
Found 1 error.
```

In two case it can compile but error is here

**Comment by Fuco1** [comment] 2019-02-22 15:17
I'm doing the type-check on *my* program which uses this library as dependency.  But I can not compile my code because I get the error in OP.

I'm no typescript expert so I'm not sure what the solution is.

**Comment by Its-Alex** [comment] 2019-02-22 15:18
Okay, I will check this weekend thanks for reporting it !

**Comment by Fuco1** [comment] 2019-02-25 14:46
I'm going to test this right away, I'll keep you updated!

**Comment by Fuco1** [comment] 2019-02-25 14:51
I now get another error

```
node_modules/winston-node-sentry/dist/index.d.ts:11:56 - error TS2339: Property 'default' does not exist on type 'typeof TransportStream'.

11 export declare class SentryTransport extends Transport.default {
                                                          ~~~~~~~


Found 1 error.
```

if I remove `.default` then it works fine.  I think the `* as Transport` already uses the default export?

**Comment by Its-Alex** [comment] 2019-02-25 16:06
For my case I can't compile without the default, can you provide me the skeleton project where I can reproduce your error ?

**Comment by Its-Alex** [comment] 2019-03-04 08:37
@Fuco1 up ?

**Comment by Fuco1** [comment] 2019-03-04 09:47
I'll try to create something but in the meantime we switched to a different package because we needed this to go live on friday

**Comment by Its-Alex** [comment] 2019-03-14 21:33
@Fuco1 up ?

**Comment by Its-Alex** [comment] 2019-05-01 07:18
I see that you import from 'winston-node-sentry/dist' that might be a cause of this error, I close this issue because you didn't answer

**Closed by Its-Alex** 2019-05-01 07:18 UTC
